import os

def report_agent(insight_text: str, chart_paths: list, descriptive_stats: dict,
                 output_dir: str = "outputs/reports", report_name: str = "analysis_report.html") -> str:
    print("➡️ Assembling report.")
    os.makedirs(output_dir, exist_ok=True)
    report_path = os.path.join(output_dir, report_name)

    # ✅ Preprocess text to avoid backslash in f-string
    formatted_text = insight_text.replace('\n', '<br>')

    # Start building HTML content
    html_content = "<html><head><title>Data Analysis Report</title></head><body>"
    html_content += "<h1 style='text-align:center;'>📊 AI Data Analysis Report</h1>"

    # ✅ Table of Contents
    html_content += """
    <h2>📋 Table of Contents</h2>
    <ul>
      <li><a href="#insights">Insights Summary</a></li>
      <li><a href="#stats">Descriptive Statistics</a></li>
      <li><a href="#charts">Visualizations</a></li>
    </ul>
    <hr>
    """

    # ✅ Insights Section
    html_content += f"""
    <h2 id="insights">🔎 Key Findings & Recommendations</h2>
    <p>{formatted_text}</p>
    <hr>
    """

    # ✅ Real Stats Table
    html_content += f"""
    <h2 id="stats">📊 Descriptive Statistics</h2>
    <table border="1" cellpadding="8" cellspacing="0">
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Total Sales</td><td>${descriptive_stats.get('total_sales', 'N/A')}</td></tr>
    <tr><td>Average Unit Price</td><td>${descriptive_stats.get('average_unit_price', 'N/A')}</td></tr>
    <tr><td>Top Performing Branch</td><td>{descriptive_stats.get('top_branch', 'N/A')}</td></tr>
    <tr><td>Average Customer Rating</td><td>{descriptive_stats.get('average_rating', 'N/A')} stars</td></tr>
    </table>
    <hr>
    """

    # ✅ Chart Visualizations
    html_content += "<h2 id='charts'>📈 Visualizations</h2>"
    html_content += "<div style='display:flex; flex-wrap:wrap; justify-content:center;'>"

    for chart in chart_paths:
        html_content += f"""
        <div style="margin:10px;">
            <img src="../charts/{os.path.basename(chart)}" style="width:300px; border:1px solid #ccc; box-shadow:2px 2px 5px rgba(0,0,0,0.1);">
        </div>
        """

    html_content += "</div>"

    # ✅ Branding Footer
    html_content += """
    <hr>
    <p style="text-align:center; font-size:14px; color:gray;">
    Report generated by <b>AI Data Crew Assistant</b><br>
    Powered by LangGraph + LangChain + Gemini 1.5 Flash + Streamlit
    </p>
    </body></html>
    """

    # ✅ Write report
    with open(report_path, "w", encoding="utf-8") as file:
        file.write(html_content)

    print(f"✅ Report generated: {report_path}")
    return report_path
